spring.application.name=tp-foyer
spring.datasource.url=${TPFOYER_DB_URL:jdbc:mysql://127.0.0.1:3307/tpfoyerdb?createDatabaseIfNotExist=true}
spring.datasource.username=${TPFOYER_DB_USER:root}
spring.datasource.password=${TPFOYER_DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=${SERVER_PORT:8081}
